blank_issues_enabled: false
contact_links:
  - name: Questions / Discussions
    url: https://github.com/alif1601/ramanujan-magic-square/discussions
    about: Ask questions and share ideas in Discussions.
